-- models/staging/stg_inventory.sql

SELECT
    WAREHOUSE,
    PRODUCT_CODE,
    PRODUCT_NAME,
    BRAND,
    CATEGORY,
    SUPPLIER,
    STOCK_UNITS,
    REORDER_POINT,
    UNIT_COST_USD,
    TOTAL_INVENTORY_VALUE,
    NEEDS_REORDER::BOOLEAN  AS needs_reorder,
    SNAPSHOT_DATE::DATE     AS snapshot_date
FROM LAKEHOUSE_DB.SILVER.INVENTORY
WHERE PRODUCT_CODE IS NOT NULL